# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-18 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='debt_statu',
            new_name='debtor',
        ),
    ]
