# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-18 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtor', '0002_auto_20170518_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_due_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('customer_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('principal_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intrest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtor.tbl_due_listing')),
            ],
        ),
        migrations.DeleteModel(
            name='debtor',
        ),
    ]
